//! Numeric `AppError` codes for the published C ABI.
//!
//! The façade calls this mapping. Product decisions stay in `seyal-client::app`.

use crate::app::AppError;

pub(super) fn error_number(error: AppError) -> i32 {
    match error {
        AppError::UnknownPane => 1,
        AppError::StalePane => 2,
        AppError::StaleExecution => 3,
        AppError::StaleAttachment => 4,
        AppError::StaleController => 5,
        AppError::StalePresentationEpoch => 6,
        AppError::UnboundUnauthorized => 7,
        AppError::AlreadyBound => 8,
        AppError::NotController => 9,
        AppError::DirectInputUnauthorized => 10,
        AppError::ZeroPtyGeneration => 11,
        AppError::Frozen => 12,
        AppError::NoLiveClient => 13,
        AppError::InvalidPayload => 14,
        AppError::StaleRecoveryGeneration => 15,
        AppError::ComposerSubmitDisabled => 16,
        AppError::StaleComposerRequest => 17,
        AppError::StaleComposerEpoch => 18,
        AppError::UnknownAgent => 19,
        AppError::UnknownAttention => 20,
        AppError::UnknownChromeWorkspace => 21,
        AppError::UnknownChromeTab => 22,
        AppError::ComposerHistoryUnavailable => 23,
        AppError::ComposerHistoryClosed => 24,
        AppError::ComposerHistoryNoSelection => 25,
        AppError::PaletteNotOpen => 26,
        AppError::PaletteNoSelection => 27,
        AppError::TabCreationUnavailable => 28,
        AppError::PaneSplitUnavailable => 29,
        AppError::UnknownBlock => 30,
        AppError::CannotCloseLastTab => 31,
        AppError::CannotCloseLastPane => 32,
        AppError::CannotCloseBoundPane => 33,
        AppError::NoSplitDivider => 34,
        AppError::ProvisioningRejected => 35,
        AppError::ProvisioningCapacityExceeded => 36,
        AppError::NavigationUnsupportedKind => 37,
        AppError::NavigationDenied => 38,
        AppError::NavigationUnknownWorkspace => 39,
        AppError::NavigationUnknownTab => 40,
        AppError::NavigationUnknownPane => 41,
        AppError::NavigationUnknownExecution => 42,
        AppError::NavigationNotComposed => 43,
        AppError::NavigationTargetTerminated => 44,
        AppError::NavigationTargetUnbound => 45,
        AppError::NavigationAmbiguousTarget => 46,
        AppError::GotoNotOpen => 47,
        AppError::GotoNoSelection => 48,
        AppError::GotoUnsupportedScope => 49,
        // #1010 Block Rerun. 50 is reserved by in-flight #1212 (ActionUnavailable).
        AppError::BlockRunning => 51,
        AppError::ComposerUnavailable => 52,
        AppError::ComposerDraftOccupied => 53,
    }
}
